version: '3.8'

services:

  ecommerce-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL:postgresql://db:5432/ecommerce
      - SPRING_DATASOURCE_USERNAME:ecommerce_user
      - SPRING_DATASOURCE_PASSWORD:password@
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=ecommerce_user
      - POSTGRES_PASSWORD=password@
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: